apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    tier: backend
data:
  REDIS_HOST: "redis" 
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    project: roboshop
    component: cart
    tier: backend
  namespace: roboshop
spec: 
  selector:
    project: roboshop
    component: cart
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: cart
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: cart
        tier: backend
    spec:
      containers:
      - name: cart
        image: shanmukhatadisetti/cart:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart
        ports:
        - name: liveness-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "150m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75