apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    project: roboshop
    component: shipping
    tier: backend
  namespace: roboshop
spec: 
  selector:
    project: roboshop
    component: shipping
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: shipping
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        tier: backend
    spec:
      containers:
      - name: shipping
        image: shanmukhatadisetti/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
        ports:
        - name: liveness-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 120
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 50
          periodSeconds: 20
        resources:
          requests:
            memory: "150Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "300m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75